import{derived,phases}from './engine.js';
import{enhanceSliders}from './touch-sliders.js';
const $=id=>document.getElementById(id),defaults={T:5772,logL:0,g:4.438,z:0,useG:false,useZ:false,tolT:3,tolL:.12,tolG:.15,tolZ:.2};let q={...defaults},ready=false,manifest=null,plot=[],result=null,requestId=0,timer,visual=derived(q),rgb=[255,245,225],paused=matchMedia('(prefers-reduced-motion: reduce)').matches,phase=0;
const fmt=(n,d=3)=>!Number.isFinite(n)?'—':(Math.abs(n)>=1e5||(Math.abs(n)<.001&&n!==0)?n.toExponential(2):n.toLocaleString('en-US',{maximumSignificantDigits:d}));
const age=a=>a<6?fmt(10**a/1e3)+' kyr':a<9?fmt(10**a/1e6)+' Myr':fmt(10**a/1e9)+' Gyr';
const fields=[{key:'T',label:'Temperature',unit:'K',min:2000,max:250000,log:true,step:1,tol:'tolT',tolUnit:'%',tolMin:.1,tolMax:20,tolStep:.1,left:'2,000 K',right:'250,000 K',help:'Surface effective temperature, not core temperature.'},{key:'logL',label:'Luminosity',unit:'L☉',min:1e-5,max:1e7,log:true,step:'any',tol:'tolL',tolUnit:'dex',tolMin:.01,tolMax:1,tolStep:.01,left:'0.00001 × SUN',right:'10,000,000 × SUN',help:'Total intrinsic power over all wavelengths; ±0.12 dex is a factor of 1.32.'}];
for(const f of fields){const box=document.createElement('div');box.className='control';box.id='box-'+f.key;const label=f.toggle?`<div class="switch"><input type="checkbox" id="${f.toggle}" aria-label="Use ${f.label.toLowerCase()} measurement"><label for="${f.key}">${f.label} <small>· ${f.unit}</small></label></div>`:`<label for="${f.key}">${f.label} <small>· ${f.unit}</small></label>`;box.innerHTML=`<div class="control-head">${label}<input type="number" id="${f.key}" aria-label="${f.label}" min="${f.min}" max="${f.max}" step="${f.step}"></div><input type="range" id="${f.key}Slider" aria-label="${f.label} slider" min="${f.log?Math.log10(f.min):f.min}" max="${f.log?Math.log10(f.max):f.max}" step="${f.log?.0001:f.step}"><div class="tolerance"><label for="${f.tol}">±</label><input id="${f.tol}" aria-label="${f.label} tolerance" type="number" min="${f.tolMin}" max="${f.tolMax}" step="${f.tolStep}"><span>${f.tolUnit}</span></div>`;$('controls').append(box);
$(f.key).oninput=()=>{const v=Number($(f.key).value);if($(f.key).value===''||!Number.isFinite(v)||v<f.min||v>f.max){$(f.key).setAttribute('aria-invalid','true');return}$(f.key).removeAttribute('aria-invalid');q[f.key]=f.key==='logL'?Math.log10(v):v;setSlider(f);changed()};
$(f.key+'Slider').oninput=e=>{q[f.key]=f.key==='logL'?+e.target.value:f.log?10**(+e.target.value):+e.target.value;$(f.key).value=Number((f.key==='logL'?10**q.logL:q[f.key]).toPrecision(6));$(f.key).removeAttribute('aria-invalid');changed()};
$(f.tol).oninput=()=>{const v=Number($(f.tol).value);if($(f.tol).value===''||!Number.isFinite(v)||v<f.tolMin||v>f.tolMax){$(f.tol).setAttribute('aria-invalid','true');return}$(f.tol).removeAttribute('aria-invalid');q[f.tol]=v;changed()};if(f.toggle)$(f.toggle).onchange=()=>{q[f.toggle]=$(f.toggle).checked;syncFields();changed()}}
enhanceSliders();
function setSlider(f){$(f.key+'Slider').value=f.key==='logL'?q.logL:f.log?Math.log10(q[f.key]):q[f.key]}
function syncFields(){for(const f of fields){$(f.key).value=Number((f.key==='logL'?10**q.logL:q[f.key]).toPrecision(6));setSlider(f);$(f.tol).value=q[f.tol];$(f.key).removeAttribute('aria-invalid');$(f.tol).removeAttribute('aria-invalid');if(f.toggle){$(f.toggle).checked=q[f.toggle];$('box-'+f.key).classList.toggle('off',!q[f.toggle]);for(const id of [f.key,f.key+'Slider',f.tol])$(id).disabled=!q[f.toggle]}}}
function changed(mode='YOUR MEASUREMENTS'){$('inputMode').textContent=mode;updateVisual();schedule()}
function schedule(){clearTimeout(timer);requestId++;if(!ready)return;$('liveState').textContent='UPDATING';$('results').style.opacity='.55';const id=requestId;timer=setTimeout(()=>worker.postMessage({type:'infer',id,q}),100)}
$('reset').onclick=()=>{q={...defaults};syncFields();changed('SOLAR-LIKE EXAMPLE')};$('sizeMode').onchange=drawStar;
document.querySelectorAll('[data-example]').forEach(b=>{b.disabled=true;b.onclick=()=>{const row=manifest.examples[+b.dataset.example].row;q={...defaults,T:10**row[0],logL:row[1],g:row[2],z:row[3],useG:false,useZ:false};syncFields();changed('EXAMPLE MEASUREMENTS')}});
function pauseLabel(){$('pause').textContent=paused?'Resume':'Pause';$('pause').setAttribute('aria-pressed',String(paused))}$('pause').onclick=()=>{paused=!paused;pauseLabel()};pauseLabel();
// Planck spectrum integrated with Wyman et al. analytic CIE 1931 fits (380–780 nm).
function blackbody(T){let X=0,Y=0,Z=0;for(let nm=380;nm<=780;nm+=5){const gauss=(mu,a,b)=>Math.exp(-.5*((nm-mu)*(nm<mu?a:b))**2),x=.362*gauss(442,.0624,.0374)+1.056*gauss(599.8,.0264,.0323)-.065*gauss(501.1,.049,.0382),y=.821*gauss(568.8,.0213,.0247)+.286*gauss(530.9,.0613,.0322),z=1.217*gauss(437,.0845,.0278)+.681*gauss(459,.0385,.0725),p=1/(nm**5*Math.expm1(1.438776877e7/(nm*T)));X+=p*x;Y+=p*y;Z+=p*z}X/=Y;Z/=Y;Y=1;let c=[3.2406*X-1.5372*Y-.4986*Z,-.9689*X+1.8758*Y+.0415*Z,.0557*X-.204*Y+1.057*Z],max=Math.max(...c);return c.map(v=>{v=Math.max(0,v/max);return Math.round(255*(v<=.0031308?12.92*v:1.055*v**(1/2.4)-.055))})}
function updateVisual(){visual=derived(q);rgb=blackbody(q.T);$('radius').textContent=fmt(visual.radius)+' R☉';$('radiusRange').textContent=fmt(visual.rlo)+'–'+fmt(visual.rhi)+' R☉ · tolerance bounds';$('mass').textContent=visual.mass===null?'—':fmt(visual.mass)+' M☉';$('massRange').textContent=visual.mass===null?'No mass–luminosity assumption':fmt(visual.mlo)+'–'+fmt(visual.mhi)+' M☉ · tolerance bounds';$('color').textContent=q.T<3700?'Orange-red':q.T<5200?'Warm white':q.T<7500?'White':q.T<12000?'Blue-white':'Pale blue';$('color').style.color='rgb('+rgb+')';$('peak').textContent=fmt(visual.peak)+' nm';$('peakBand').textContent=visual.peak<380?'Ultraviolet peak':visual.peak>780?'Infrared peak':'Visible peak · broad spectrum';$('tempBadge').textContent=fmt(q.T,5)+' K';drawStar();drawHR()}
function renderResult(r,ms){result=r;$('loading').hidden=true;$('results').hidden=false;$('results').style.opacity='1';$('liveState').textContent='LIVE';let n=r.groups.length;document.getElementById('quickVerdict').textContent=n===0?'No compatible sampled model':n===1?'Grid match: '+phases[r.groups[0].phase].name:n+' phases compatible · '+r.groups.map(p=>phases[p.phase].name).join(' / ');$('verdictKind').textContent=n===0?'NO COMPATIBLE GRID POINT':n===1?'ONE PHASE IN THIS GRID':'AMBIGUITY RETAINED';$('verdict').textContent=n===0?'No match in the sampled grid':n===1?phases[r.groups[0].phase].name:n+' evolutionary phases fit';$('verdictText').textContent=n===0?'No sampled model satisfies every enabled measurement window. This is not a claim that such a star cannot exist.':n===1?'These measurements select one phase among the models sampled here. Other model physics or unrepresented stars may change that conclusion.':'Your measurements do not yet distinguish these phases. All are retained; the first card is the closest sampled match, not necessarily the most probable stage.';
if(r.groups.length){const lo=Math.min(...r.groups.map(p=>p.mass[0])),hi=Math.max(...r.groups.map(p=>p.mass[1]));$('mass').textContent=fmt(lo)+'–'+fmt(hi)+' M☉'}else{$('mass').textContent='—'}
$('stageCards').innerHTML=r.groups.map(p=>{const s=phases[p.phase];return `<span class="stage-chip" style="--phase:${s.color}">${s.name}</span>`}).join('');
$('verdict').textContent=n===0?'No grid match':n===1?'':'Ambiguous · '+n+' phases';
let next;if(!n)next='Check units and enabled inputs, then widen tolerances if justified. The grid is finite and excludes binaries, rotation, and some compositions; do not force an evolutionary label.';else if(!q.useG)next='Next useful measurement: surface gravity. It gives a mass through GM/R² and can exclude some of the currently compatible models.';else if(!q.useZ)next='Next useful measurement: surface composition. Enable it only with an appropriate bulk metal/H estimate; iron abundance alone may not represent this quantity.';else if(n>1)next='The supplied measurements still overlap. More precise measurements may help; some giant phases require additional diagnostics such as stellar oscillations. This version does not fit those diagnostics.';else next='One sampled phase fits. The classification is conditional on measurement tolerances and the model grid—not a uniquely proven history.';$('nextMeasurement').textContent=next;
$('fitNote').textContent=`${r.count.toLocaleString()} matching points of ${manifest.total_rows.toLocaleString()} · ${r.dims} enabled observables · exhaustive sampled-grid matching. Ranges are extrema, not confidence intervals.`;drawHR()}
let worker;try{worker=new Worker(new URL('./worker.js',import.meta.url),{type:'module'});worker.onmessage=e=>{const d=e.data;if(d.type==='progress'){$('loadProgress').value=d.done/d.total;$('loadText').textContent=fmt(d.done/1e6)+' / '+fmt(d.total/1e6)+' MB'}else if(d.type==='ready'){manifest=d.manifest;plot=d.plot;ready=true;$('dataSummary').innerHTML=`<p><b>Loaded data:</b> ${manifest.total_rows.toLocaleString()} points from MIST 1.2 / MESA 7503. Initial [Fe/H] grid: −2.0 to +0.5 in 0.25 dex steps; [α/Fe] = 0; initial rotation v/vcrit = 0. Ages are log₁₀(age/yr) = 5.0–10.10 in 0.05 dex steps (0.1 Myr to 12.59 Gyr). All tabulated EEPs in this subset are retained. The 13.8 Gyr upper-age filter does not create unprovided intermediate ages.</p><p><b>Gravity consistency:</b> model gravitational acceleration is recomputed from published current mass and the Stefan–Boltzmann radius. Separately tabulated MIST log g is not used: in this grid it can imply mass discrepancies up to ${(100*manifest.validation.max_relative_mass_difference_if_raw_MIST_log_g_were_used).toFixed(1)}% with the other columns. The app preserves M = gR²/G consistently. Published log-radius and recomputed radius agree within ${(100*manifest.validation.max_relative_radius_difference_from_MIST).toFixed(3)}%.</p>`;document.querySelectorAll('[data-example]').forEach(b=>b.disabled=false);schedule();drawHR()}else if(d.type==='result'&&d.id===requestId)renderResult(d.result,d.ms);else if(d.type==='error')fail(d.message)};worker.onerror=e=>fail(e.message)}catch(e){fail(e.message)}
function fail(message){$('liveState').textContent='LOAD ERROR';$('loading').hidden=false;$('loading').innerHTML='<h3 class="error">Models could not load</h3><p id="errorText"></p><p>The physical calculations still work. Reload in a current browser with an internet connection to retry classification.</p>';$('errorText').textContent=message}
function context(id){const c=$(id),w=c.clientWidth,h=c.clientHeight,d=Math.min(devicePixelRatio||1,2);if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const g=c.getContext('2d');g.setTransform(d,0,0,d,0,0);g.clearRect(0,0,w,h);return{g,w,h}}
function drawStar(){const{g,w,h}=context('star'),linear=$('sizeMode').value==='linear',ratio=linear?visual.radius:visual.radius**.18,max=Math.min(w*.2,h*.29),unit=max/Math.max(ratio,1),r=Math.max(.6,unit*ratio),sun=Math.max(.6,unit),x=w*.67,y=h*.49,sx=w*.26;for(let i=0;i<95;i++){g.fillStyle='rgba(190,214,247,'+(.08+(i%4)*.045)+')';g.fillRect((Math.sin(i*83.2)*.5+.5)*w,(Math.cos(i*54.3)*.5+.5)*h,1,1)}const halo=g.createRadialGradient(x,y,r*.75,x,y,r*2);halo.addColorStop(0,'rgba('+rgb+','+(.16+.5*(q.logL+5)/12)+')');halo.addColorStop(1,'rgba('+rgb+',0)');g.fillStyle=halo;g.beginPath();g.arc(x,y,r*2,0,Math.PI*2);g.fill();g.save();g.beginPath();g.arc(x,y,r,0,Math.PI*2);g.clip();const grad=g.createRadialGradient(x-r*.2,y-r*.25,0,x,y,r);grad.addColorStop(0,'rgb('+rgb+')');grad.addColorStop(.7,'rgb('+rgb.map(v=>Math.round(v*.84))+')');grad.addColorStop(1,'rgb('+rgb.map(v=>Math.round(v*.4))+')');g.fillStyle=grad;g.fillRect(x-r,y-r,2*r,2*r);for(let i=0;i<420;i++){const u=((i*.61803398875+phase*.004)%1)*2-1,v=Math.sin(i*17.7)*.97;if(u*u+v*v>.97)continue;g.fillStyle=i%3?'rgba(25,10,8,.07)':'rgba(255,255,240,.1)';g.beginPath();g.ellipse(x+u*r,y+v*r,Math.max(.3,r*.023*Math.sqrt(1-u*u)),Math.max(.3,r*.01),0,0,Math.PI*2);g.fill()}g.restore();g.strokeStyle='#a8b2bd';g.lineWidth=.8;g.setLineDash([2,3]);g.beginPath();g.arc(sx,y,sun,0,Math.PI*2);g.stroke();g.setLineDash([]);g.font='10px system-ui';g.textAlign='center';g.fillStyle='#96a7bc';g.fillText('SUN · 1 R☉',sx,Math.min(h-52,y+sun+22));g.fillStyle='#d5e4f6';g.fillText('YOUR STAR',x,Math.min(h-52,y+r+22));g.textAlign='left';$('viewLabel').textContent=linear?'True radius ratio · auto zoom · tiny objects shown as markers':'Compressed radii · artistic surface motion'}
function drawHR(){const{g,w,h}=context('hr'),left=47,right=w-17,top=15,bottom=h-33,px=t=>left+(5.4-t)/2.1*(right-left),py=l=>bottom-(l+5)/12*(bottom-top);g.font='10px system-ui';for(let l=-4;l<=6;l+=2){const y=py(l);g.strokeStyle='#233148';g.beginPath();g.moveTo(left,y);g.lineTo(right,y);g.stroke();g.fillStyle='#859ab5';g.fillText('10^'+l,3,y+3)}g.save();g.beginPath();g.rect(left,top,right-left,bottom-top);g.clip();for(const p of plot){g.fillStyle=phases[Math.round(p[2])]?.color+'50';g.fillRect(px(p[0]),py(p[1]),1.3,1.3)}const x1=px(Math.log10(q.T*(1+q.tolT/100))),x2=px(Math.log10(q.T*(1-q.tolT/100))),y1=py(q.logL+q.tolL),y2=py(q.logL-q.tolL);g.fillStyle='#ffffff16';g.fillRect(x1,y1,x2-x1,y2-y1);g.strokeStyle='#f4fcff';g.strokeRect(x1,y1,Math.max(1,x2-x1),Math.max(1,y2-y1));g.fillStyle='rgb('+rgb+')';g.beginPath();g.arc(px(Math.log10(q.T)),py(q.logL),4,0,Math.PI*2);g.fill();g.stroke();g.restore();for(const t of [200000,20000,2000]){g.textAlign=t===200000?'left':t===2000?'right':'center';g.fillStyle='#a1b3cb';g.fillText(t.toLocaleString()+' K',px(Math.log10(t)),h-9)}g.textAlign='left';g.fillStyle='#aec8d3';g.font='9px system-ui';g.fillText('L / L☉',left,10)}
$('legend').innerHTML=Object.values(phases).map(p=>`<span><i style="background:${p.color}"></i>${p.name}</span>`).join('');window.addEventListener('resize',()=>{drawStar();drawHR()});let last=0;function animate(now){if(now-last>33){if(!paused&&!document.hidden){phase+=Math.min((now-last)/1000,.1);drawStar()}last=now}requestAnimationFrame(animate)}syncFields();updateVisual();requestAnimationFrame(animate);
// Read-only diagnostics for reproducible browser verification.
window.starLab={get state(){return{...q}},get result(){return result},get ready(){return ready},get physical(){return{...visual}}};
