export const C={sigma:5.670374419e-8,Lsun:3.828e26,Rsun:6.957e8,Msun:1.98847e30,G:6.67430e-11};
export const phases={'-1':{name:'Pre-main sequence',color:'#d5a1ff',description:'Contracting before sustained core hydrogen burning.'},'0':{name:'Main sequence',color:'#88ddff',description:'Core hydrogen-burning phase in MIST.'},'2':{name:'Post-main sequence / red giant branch',color:'#ffb788',description:'After the main sequence, including expansion toward the red-giant branch. This grid flag does not separately resolve every subgiant stage.'},'3':{name:'Core helium burning',color:'#ffd778',description:'Helium burning in the core; can overlap the red-giant branch in temperature and luminosity.'},'4':{name:'Early asymptotic giant branch',color:'#efa5ce',description:'Early asymptotic giant branch after core helium exhaustion.'},'5':{name:'Thermally pulsing asymptotic giant branch',color:'#f784a1',description:'Late asymptotic giant branch with thermal pulses.'},'6':{name:'Post-asymptotic giant branch / white dwarf cooling',color:'#a6b5ff',description:'MIST combines post-asymptotic giant branch evolution and the white-dwarf cooling sequence in this flag. This app does not falsely split them.'},'9':{name:'Wolf–Rayet flag',color:'#9fe0c2',description:'MIST Wolf–Rayet designation; can overlap core hydrogen burning for very massive stars.'}};
export function radius(T,L){return Math.sqrt(L*C.Lsun/(4*Math.PI*C.sigma*T**4))/C.Rsun}
export function massFromGravity(r,logg){return 10**logg/100*(r*C.Rsun)**2/C.G/C.Msun}
export function derived(q){const r=radius(q.T,10**q.logL),tlo=q.T*(1-q.tolT/100),thi=q.T*(1+q.tolT/100),rlo=radius(thi,10**(q.logL-q.tolL)),rhi=radius(tlo,10**(q.logL+q.tolL));return{radius:r,rlo,rhi,mass:q.useG?massFromGravity(r,q.g):null,mlo:q.useG?massFromGravity(rlo,q.g-q.tolG):null,mhi:q.useG?massFromGravity(rhi,q.g+q.tolG):null,peak:2.897771955e6/q.T}}
export function infer(chunks,q){const logT=Math.log10(q.T),tlo=Math.log10(q.T*(1-q.tolT/100)),thi=Math.log10(q.T*(1+q.tolT/100)),tw=(thi-tlo)/2,groups={},dims=2+Number(q.useG)+Number(q.useZ);let count=0,nearest=null,unavailableComposition=0;
for(const a of chunks){for(let i=0;i<a.length;i+=9){const t=a[i],l=a[i+1],g=a[i+2],z=a[i+3],phase=Math.round(a[i+7]);if(q.useZ&&z===99){unavailableComposition++;continue}const dt=(t-logT)/tw,dl=(l-q.logL)/q.tolL,dg=q.useG?(g-q.g)/q.tolG:0,dz=q.useZ?(z-q.z)/q.tolZ:0,score=dt*dt+dl*dl+dg*dg+dz*dz;
if(!nearest||score<nearest.score)nearest={score,row:Array.from(a.subarray(i,i+9))};
if(t<tlo||t>thi||Math.abs(dl)>1||Math.abs(dg)>1||Math.abs(dz)>1)continue;
count++;let p=groups[phase];if(!p)p=groups[phase]={phase,count:0,score:Infinity,mass:[Infinity,-Infinity],age:[Infinity,-Infinity],initialMass:[Infinity,-Infinity],gravity:[Infinity,-Infinity],metals:[Infinity,-Infinity]};p.count++;p.mass[0]=Math.min(p.mass[0],a[i+4]);p.mass[1]=Math.max(p.mass[1],a[i+4]);p.age[0]=Math.min(p.age[0],a[i+5]);p.age[1]=Math.max(p.age[1],a[i+5]);p.initialMass[0]=Math.min(p.initialMass[0],a[i+6]);p.initialMass[1]=Math.max(p.initialMass[1],a[i+6]);p.gravity[0]=Math.min(p.gravity[0],g);p.gravity[1]=Math.max(p.gravity[1],g);if(z!==99){p.metals[0]=Math.min(p.metals[0],z);p.metals[1]=Math.max(p.metals[1],z)}if(score<p.score){p.score=score;p.best=Array.from(a.subarray(i,i+9))}}
}return{groups:Object.values(groups).sort((a,b)=>a.score-b.score),count,nearest,dims,unavailableComposition}}
