const{chromium}=require('../stellar-properties-lab/node_modules/playwright-core');const assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.waitForFunction(()=>starLab.ready&&starLab.modelReady);await p.locator('#lithiumChoice').tap();
const cross=await p.locator('.lithium-crossing-label').innerText();assert.match(cross,/50 \/ 50 at/);const value=Number(cross.match(/at ([\d.]+)/)[1]);assert.ok(value>65&&value<85);
const original=await p.locator('.lithium-crossover').getAttribute('style');assert.ok(await p.locator('.lithium-color-rail').evaluate(e=>getComputedStyle(e).backgroundImage.includes('gradient')));
assert.match(await p.locator('.lithium-main').innerText(),/main sequence/);assert.match(await p.locator('.lithium-young').innerText(),/pre-main sequence/);
const set=async(id,value)=>p.evaluate(({id,value})=>{const s=document.getElementById(id+'Slider');s.value=value;s.dispatchEvent(new Event('input'))},{id,value});
await set('lithium',value);const diff=await p.evaluate(()=>Math.abs(starLab.ranking.rows[0].percent-starLab.ranking.rows[1].percent));assert.ok(diff<5);
await set('lithium',20);assert.equal(await p.evaluate(()=>starLab.ranking.rows[0].phase),0);await set('lithium',150);assert.equal(await p.evaluate(()=>starLab.ranking.rows[0].phase),-1);
await p.screenshot({path:'validation/v13-'+(process.env.TEST_URL?'live-':'')+'lithium.png',fullPage:true});
await set('T',Math.log10(5800));await p.waitForFunction(()=>starLab.modelReady);await p.locator('#lithiumChoice').tap();assert.notEqual(await p.locator('.lithium-crossover').getAttribute('style'),original);
for(const width of [320,390,430]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
const slider=p.locator('#lithiumSlider');await slider.scrollIntoViewIfNeeded();const rect=await slider.boundingBox(),before=await p.evaluate(()=>scrollY),cdp=await p.context().newCDPSession(p),y=rect.y+rect.height/2;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:rect.x+rect.width*.2,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:rect.x+rect.width*.7,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(Math.abs(await p.evaluate(()=>scrollY)-before)<2);assert.ok(await p.evaluate(()=>starLab.state.lithium>250));await cdp.detach();assert.deepEqual(errors,[]);
const report={passed:true,crossoverMilliangstroms:value,url:p.url(),checks:['equal-fit crossover agrees with ranking','gradient and labels','leader changes either side','recomputed for temperature','phone overflow','touch drag capture']};fs.writeFileSync('validation/v13-'+(process.env.TEST_URL?'live':'browser')+'.json',JSON.stringify(report,null,2));console.log(report);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
