const{chromium}=require('../stellar-properties-lab/node_modules/playwright-core');const assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.waitForFunction(()=>starLab.ready&&starLab.modelReady);await p.locator('#spectrumChoice').tap();
const result=await p.evaluate(async()=>{const{magnesiumScale}=await import('./magnesium-scale.js?v=17'),{rank}=await import('./ranking.js?v=12'),spectrum=await(await fetch('data/spectral-index.json')).json(),q=starLab.state,groups=starLab.candidates,s=magnesiumScale(groups,q,spectrum);let last=-1,maxError=0;for(let i=0;i<=1000;i++){const x=s.toValue(i/1000);if(x<=last)throw Error('Not monotonic');last=x;if(Math.abs(s.toPosition(x)-i/1000)>1e-10)throw Error('Inverse mismatch');const r=rank(groups,{...q,wing:x},{spectrum}),a=s.at(x);for(const row of a||[])maxError=Math.max(maxError,Math.abs(row.percent-r.rows.find(v=>v.phase===row.phase).percent))}window.magnesiumTestScale=s;return{peaks:s.peaks,markers:s.crossings.map(x=>s.toPosition(x)*100),maxError,positions:Object.fromEntries(Object.entries(s.peaks).map(([k,v])=>[k,s.toPosition(v.x)*1000]))}});
assert.ok(result.peaks['0'].percent>53&&result.peaks['0'].percent<55);assert.ok(result.peaks['-1'].percent>99.9);assert.equal(result.maxError,0);assert.equal(result.markers.length,4);for(let i=1;i<4;i++)assert.ok(result.markers[i]-result.markers[i-1]>20);
for(const phase of ['-1','0']){await p.locator('#wingSlider').evaluate((e,value)=>{e.value=value;e.dispatchEvent(new Event('input'))},result.positions[phase]);assert.equal(await p.evaluate(()=>String(starLab.ranking.rows[0].phase)),phase);const actual=await p.evaluate(()=>starLab.ranking.rows[0].percent);assert.ok(Math.abs(actual-result.peaks[phase].percent)<.01)}
await p.screenshot({path:'validation/v17-'+(process.env.TEST_URL?'live-':'')+'magnesium.png',fullPage:true});
const slider=p.locator('#wingSlider');await slider.scrollIntoViewIfNeeded();const rect=await slider.boundingBox(),cdp=await p.context().newCDPSession(p),y=rect.y+rect.height/2,scroll=await p.evaluate(()=>scrollY);for(const ratio of [.1,.5,.9]){const x=rect.x+15+(rect.width-30)*ratio;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const error=await p.evaluate(r=>Math.abs(starLab.state.wing-magnesiumTestScale.toValue(r)),ratio);assert.ok(error<1e-6)}await cdp.detach();assert.ok(Math.abs(await p.evaluate(()=>scrollY)-scroll)<2);
for(const width of [320,390,430]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}assert.deepEqual(errors,[]);const out={passed:true,url:p.url(),...result};fs.writeFileSync('validation/v17-'+(process.env.TEST_URL?'live':'browser')+'.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
