const{chromium}=require('../stellar-properties-lab/node_modules/playwright-core');const assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const b=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',headless:true});try{const p=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(String(e)));await p.goto(process.env.TEST_URL||'http://127.0.0.1:8768/');await p.waitForFunction(()=>starLab.ready&&starLab.modelReady);await p.locator('#lithiumChoice').tap();const before=await p.evaluate(()=>starLab.ranking.rows.map(r=>r.percent));assert.equal(await p.locator('#candidateList button:disabled').count(),0);await p.locator('#candidateList button').nth(0).tap();const first=await p.evaluate(()=>starLab.selected);await p.locator('#candidateList button').nth(1).tap();assert.notEqual(await p.evaluate(()=>starLab.selected),first);await p.locator('#candidateList button').nth(0).tap();assert.equal(await p.evaluate(()=>starLab.selected),first);assert.deepEqual(await p.evaluate(()=>starLab.ranking.rows.map(r=>r.percent)),before);
await p.locator('#noneChoice').tap();const set=async(id,v)=>p.locator('#'+id+'Slider').evaluate((e,v)=>{e.value=v;e.dispatchEvent(new Event('input'))},v);await set('T',Math.log10(4800));await set('logL',Math.log10(50));await p.waitForFunction(()=>starLab.modelReady);await p.locator('#seismicChoice').tap();
for(const id of ['Dnu','numax','DPi1']){assert.ok(await p.locator('#'+id+'Key').isVisible());assert.match(await p.locator('#'+id+'Key').innerText(),/Orange: shell-burning giants/);assert.ok(await p.locator('#'+id+'Slider').evaluate(e=>getComputedStyle(e.parentNode.querySelector('.lithium-color-rail')).backgroundImage.includes('gradient')))}
await p.getByRole('button',{name:'Explore shell-burning measurements',exact:true}).tap();
const check=await p.evaluate(async()=>{const{oscillationScale}=await import('./oscillation-scale.js?v=19'),{rank}=await import('./ranking.js?v=19'),read=async n=>await(await fetch('data/'+n+'.json')).json(),data={evidence:await read('evidence'),seismic:await read('seismic-density'),spectrum:await read('spectral-index')},q=starLab.state,groups=[2,3].map(phase=>({phase,solutions:[{mass:1,age:9,metallicity:0}]})),scales={};for(const id of ['Dnu','numax','DPi1']){const el=document.getElementById(id+'Slider'),s=oscillationScale(id,q,data,+el.min,+el.max);for(const x of s.crossings){const r=s.at(x);if(Math.abs(r.helium-.5)>1e-5)throw Error('Crossover not 50/50')}const r=s.at(q[id]),ranked=rank(groups,{...q,measurements:['seismic']},data);if(r&&Math.abs(r.helium*100-ranked.rows.find(r=>r.phase===3).percent)>1e-9)throw Error('Color mismatch');scales[id]=s.crossings}return scales});
assert.ok(check.DPi1.length>0);
await p.screenshot({path:'validation/v19-'+(process.env.TEST_URL?'live-':'')+'oscillations.png',fullPage:true});
const old=await p.locator('#DnuKey').innerText();await set('DPi1',100);assert.notEqual(await p.locator('#DnuKey').innerText(),old);assert.equal(await p.locator('#candidateList button:disabled').count(),0);
for(const width of [320,390,430]){await p.setViewportSize({width,height:844});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}assert.deepEqual(errors,[]);const out={passed:true,url:p.url(),crossovers:check,checks:['switch freely between candidates without changing scores','three oscillation gradient tracks','class fit matches density ranking','equal-fit markers','other controls update crossovers','unsupported candidates selectable','phone overflow']};fs.writeFileSync('validation/v19-'+(process.env.TEST_URL?'live':'browser')+'.json',JSON.stringify(out,null,2));console.log(out);
}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
